-- DROP AND CREATE DATABASE
drop database if exists `order-directory`;
create database `order-directory` ;
use `order-directory`;

-- DROP AND CREATE TABLES
DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER(
SUPP_ID int primary key,
SUPP_NAME varchar(150) NOT NULL,
SUPP_CITY varchar(80) NOT NULL,
SUPP_PHONE varchar(10) NOT NULL);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
CUS_ID INT NOT NULL primary KEY,
CUS_NAME VARCHAR(200) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY varchar(50) NOT NULL,
CUS_GENDER CHAR);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
CAT_ID INT NOT NULL PRIMARY KEY,
CAT_NAME VARCHAR(200) NOT NULL);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
PRO_ID INT NOT NULL PRIMARY KEY,
PRO_NAME VARCHAR(50) NOT NULL,
PRO_DESC VARCHAR(200),
CAT_ID INT NOT NULL,
FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (CAT_ID)
);

DROP TABLE IF EXISTS SUPPLIER_PRICING;
CREATE TABLE SUPPLIER_PRICING (
PRICING_ID INT NOT NULL PRIMARY KEY,
PRO_ID INT NOT NULL,
SUPP_ID INT NOT NULL,
SUPP_PRICE INT DEFAULT 0,
FOREIGN KEY (PRO_ID) REFERENCES PRODUCT (PRO_ID),
FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID)
);

DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER` (
ORD_ID INT NOT NULL PRIMARY KEY,
ORD_AMOUNT INT NOT NULL,
ORD_DATE DATE,
CUS_ID INT NOT NULL,
PRICING_ID INT NOT NULL,
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID)
);

DROP TABLE IF EXISTS RATING;
CREATE TABLE IF NOT EXISTS RATING (
RAT_ID INT NOT NULL,
ORD_ID INT NOT NULL,
RAT_RATSTARS INT NOT NULL,
PRIMARY KEY (RAT_ID),
FOREIGN KEY (ORD_ID) REFERENCES `order`(ORD_ID)
);